apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - port: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: crud-service
spec:
  type: ClusterIP
  selector:
    app: curd-app
  ports:
    - port: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      containers:
        - name: curd-app
          imagePullPolicy: Never
          image: final_assignment-backend
          env:
            - name: db_address
              value: db-service.default.svc.cluster.local
            - name: db_username
              value: postgres
            - name: db_name
              value: postgres
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: DB_PASSWORD

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: db
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
data:
  DB_PASSWORD: QXAwMHJQYSQkdzByZCEK
