apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: crud-app
  labels:
    app: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: db
          image: postgres:16
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-vol
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: DB_PASSWORD
      volumes:
        - name: db-vol
          persistentVolumeClaim:
            claimName: db-store-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: crud-app
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - port: 5432

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-store
  namespace: crud-app
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/rishabh/workspace/persistent
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-store-claim
  namespace: crud-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 95Mi
